LPS-121274 Create context to avoid passing all props between components
p2kmgcl/liferay-portal pull request #709
Opened 2020-09-24 08:23 UTC by sandrodw3

2020-09-24 08:23 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-09-24 15:58 UTC, p2kmgcl requested changes

2020-09-24 15:58 UTC, p2kmgcl commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SetSidebarPanelIdContext.js
> +	<SetSidebarPanelIdContext.Provider value={setSidebarPanelId}>
With this context you've moved `setSidebarPanelId` to a context, you can now access the "setBlabla" function from other components. However, there is a dependency between this context and `AppLayout`, which needs to create a real "state", and pass the information to the provider. Although it is not necessarily something wrong, it decreases the context usability because you would need to look at `AppLayout` to understand how it works.

If you move the whole state creation to `SetSidebarPanelIdProvider` (and maybe rename it to `SidebarPanelIdProvider`), then AppLayout context can forget about this logic and just use the context as any other component.

2020-09-24 15:58 UTC, p2kmgcl commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SelectedMenuItemIdContext.js
> +	<SelectedMenuItemIdContext.Provider value={selectedMenuItemId}>
Same reasoning than `SetSidebarPanelIdContext`, try to keep al context logic inside the context provider

2020-09-24 15:58 UTC, p2kmgcl commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				selected={selectedMenuItemId === item.siteNavigationMenuItemId}
This property can be removed and use `selectedMenuItem` context inside `MenuItem`

2020-09-24 15:58 UTC, p2kmgcl commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				onSelect={() => onSelectMenuItem(item)}
This property can be removed and use `setSelectedMenuItemId` context inside `MenuItem` :smile:

2020-09-24 17:36 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SetSidebarPanelIdContext.js
> +	<SetSidebarPanelIdContext.Provider value={setSidebarPanelId}>
Makes a lot of sense 😃🚀

2020-09-24 17:37 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SelectedMenuItemIdContext.js
> +	<SelectedMenuItemIdContext.Provider value={selectedMenuItemId}>
🐸

2020-09-24 17:37 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				selected={selectedMenuItemId === item.siteNavigationMenuItemId}
🐼

2020-09-24 17:38 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				onSelect={() => onSelectMenuItem(item)}
🦀 (I just realized this crab is doing the handsheart emoji)

2020-09-24 18:29 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				onSelect={() => onSelectMenuItem(item)}
Done 😋

2020-09-24 18:29 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/components/Menu.js
> +				selected={selectedMenuItemId === item.siteNavigationMenuItemId}
Done ⭐️

2020-09-24 18:30 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SelectedMenuItemIdContext.js
> +	<SelectedMenuItemIdContext.Provider value={selectedMenuItemId}>
Done 🤝

2020-09-24 18:30 UTC, sandrodw3 commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SetSidebarPanelIdContext.js
> +	<SetSidebarPanelIdContext.Provider value={setSidebarPanelId}>
Changed 🥳

2020-09-25 06:03 UTC, p2kmgcl requested changes

2020-09-25 06:03 UTC, p2kmgcl commented on modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/site_navigation_menu_editor/contexts/SelectedMenuItemIdContext.js
> +		<SelectedMenuItemIdContext.Provider
Two extra optimizations:
1. Always avoid sending an inline object to a context value, as it will be recreated every time your context provider renders, and cause more rerenders than needed.
2. There is an optimization that we are using in Page Editor that is using two separate contexts: one for the setter and another one for the state. Have a look at this article from KenCDodds that explains why :smile: https://kentcdodds.com/blog/how-to-optimize-your-context-value

2020-09-25 11:59 UTC, p2kmgcl commented
https://github.com/liferay-echo/liferay-portal/pull/2478

2020-09-25 11:59 UTC, closed without merging